import Foundation

/// The consolidated transcript document — the "SouthCreek Interview
/// Transcripts" format: ONE page per project (or per folder when no project
/// matches) holding an index table and one child page per clip. No more
/// hundred single-clip documents.
enum NotionDoc {

    struct Handle {
        let pageId: String
        let tableId: String?
        var existingClips: Set<String>   // child-page titles already present
    }

    // MARK: - HTTP plumbing (sync, same style as NotionClient)

    private static func request(_ urlString: String, method: String,
                                body: [String: Any]?, config: Config) -> [String: Any]? {
        guard let url = URL(string: urlString) else { return nil }
        var req = URLRequest(url: url)
        req.httpMethod = method
        req.setValue("Bearer \(config.notionToken)", forHTTPHeaderField: "Authorization")
        req.setValue("2022-06-28", forHTTPHeaderField: "Notion-Version")
        req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        if let body { req.httpBody = try? JSONSerialization.data(withJSONObject: body) }

        let sema = DispatchSemaphore(value: 0)
        var out: [String: Any]? = nil
        URLSession.shared.dataTask(with: req) { data, response, _ in
            defer { sema.signal() }
            guard let data, let http = response as? HTTPURLResponse else { return }
            let json = try? JSONSerialization.jsonObject(with: data) as? [String: Any]
            if (200...299).contains(http.statusCode) {
                out = json ?? [:]
            } else {
                Log.write("Notion \(method) \(url.lastPathComponent) failed (\(http.statusCode)): \((json?["message"] as? String) ?? "?")")
            }
        }.resume()
        _ = sema.wait(timeout: .now() + 20)
        return out
    }

    private static func text(_ s: String) -> [[String: Any]] {
        [["text": ["content": String(s.prefix(1900))]]]
    }

    // MARK: - Document find-or-create

    /// `baseName`: project name or folder display name. Doc title follows the
    /// SouthCreek convention: "<Base> Interview Transcripts".
    static func findOrCreate(baseName: String, projectPageId: String?,
                             sourcePath: String, config: Config) -> Handle? {
        let title = "\(baseName) Interview Transcripts"

        // Existing doc?
        if let found = request("https://api.notion.com/v1/databases/\(config.documentsDB)/query",
                               method: "POST",
                               body: ["filter": ["property": "Name", "title": ["equals": title]]],
                               config: config),
           let results = found["results"] as? [[String: Any]],
           let first = results.first, let id = first["id"] as? String {
            var h = Handle(pageId: id, tableId: nil, existingClips: [])
            loadChildren(into: &h, config: config)
            return h
        }

        // Create: intro + index table (header row).
        var properties: [String: Any] = [
            "Name": ["title": text(title)],
            "Tags": ["multi_select": [["name": "Transcript"], ["name": "Auto"]]]
        ]
        if let pid = projectPageId {
            properties["Project"] = ["relation": [["id": pid]]]
        }
        let children: [[String: Any]] = [
            ["object": "block", "type": "paragraph",
             "paragraph": ["rich_text": text("WhisperX transcriptions of interview clips from \(sourcePath). Generated by Notion Transcribe — one child page per clip, index below.")]],
            ["object": "block", "type": "table",
             "table": ["table_width": 3, "has_column_header": true, "has_row_header": false,
                       "children": [["object": "block", "type": "table_row",
                                     "table_row": ["cells": [text("Clip"), text("Subject"), text("Length")]]]]]]
        ]
        guard let created = request("https://api.notion.com/v1/pages", method: "POST",
                                    body: ["parent": ["database_id": config.documentsDB],
                                           "properties": properties,
                                           "children": children],
                                    config: config),
              let id = created["id"] as? String else { return nil }
        Log.write("Created transcript doc: \(title)")
        var h = Handle(pageId: id, tableId: nil, existingClips: [])
        loadChildren(into: &h, config: config)
        return h
    }

    /// Fills tableId + existing child-page titles (paginated) — the resume
    /// mechanism: a clip whose child page exists is already done.
    private static func loadChildren(into handle: inout Handle, config: Config) {
        var cursor: String? = nil
        var tableId: String? = nil
        var titles: Set<String> = []
        for _ in 0..<20 {
            var urlStr = "https://api.notion.com/v1/blocks/\(handle.pageId)/children?page_size=100"
            if let c = cursor { urlStr += "&start_cursor=\(c)" }
            guard let page = request(urlStr, method: "GET", body: nil, config: config),
                  let results = page["results"] as? [[String: Any]] else { break }
            for b in results {
                if b["type"] as? String == "table", tableId == nil {
                    tableId = b["id"] as? String
                }
                if b["type"] as? String == "child_page",
                   let t = (b["child_page"] as? [String: Any])?["title"] as? String {
                    titles.insert(t)
                }
            }
            if page["has_more"] as? Bool == true, let next = page["next_cursor"] as? String {
                cursor = next
            } else { break }
        }
        handle = Handle(pageId: handle.pageId, tableId: tableId, existingClips: titles)
    }

    // MARK: - Per-clip

    /// Child page inside the doc: "Clip: <name>", divider, timestamped
    /// paragraphs. Batches past Notion's per-request block cap.
    static func addClipPage(to handle: Handle, clipTitle: String, clipName: String,
                            paragraphs: [String], config: Config) -> Bool {
        var blocks: [[String: Any]] = [
            ["object": "block", "type": "paragraph",
             "paragraph": ["rich_text": text("Clip: \(clipName)")]],
            ["object": "block", "type": "divider", "divider": [:] as [String: Any]]
        ]
        blocks += paragraphs.map {
            ["object": "block", "type": "paragraph", "paragraph": ["rich_text": text($0)]]
        }

        let first = Array(blocks.prefix(88))
        guard let created = request("https://api.notion.com/v1/pages", method: "POST",
                                    body: ["parent": ["page_id": handle.pageId],
                                           "properties": ["title": ["title": text(clipTitle)]],
                                           "children": first],
                                    config: config),
              let subId = created["id"] as? String else { return false }

        var rest = Array(blocks.dropFirst(88))
        while !rest.isEmpty {
            let batch = Array(rest.prefix(88))
            rest = Array(rest.dropFirst(88))
            if request("https://api.notion.com/v1/blocks/\(subId)/children", method: "PATCH",
                       body: ["children": batch], config: config) == nil {
                Log.write("Warning: transcript tail batch failed for \(clipTitle)")
                break
            }
        }
        return true
    }

    static func addIndexRow(to handle: Handle, clip: String, subject: String,
                            length: String, config: Config) {
        guard let tableId = handle.tableId else { return }
        _ = request("https://api.notion.com/v1/blocks/\(tableId)/children", method: "PATCH",
                    body: ["children": [["object": "block", "type": "table_row",
                                         "table_row": ["cells": [text(clip), text(subject), text(length)]]]]],
                    config: config)
    }
}
